name = "backend"
compatibility_date = "2024-08-09"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzY1NzdmNjgtN2MwZS00YmZkLTliMTMtNDkyMjc2MTg0NjM2IiwidGVuYW50X2lkIjoiMmMwYWQ5YzJhODEzZThhZjVkNTJhYTUyMGMxNjE3ODZiY2I2ZDlhNTk5YzRjOWRjMWExMGQ5ZjQ2OWI4OGM0NSIsImludGVybmFsX3NlY3JldCI6IjY1NWQzMDQyLTBlMTItNGJhMi04Y2M2LTc4ODJmZGYxNjQ4OCJ9.izYN0u-Y5Xvh1nm9l0yNnml-bnxZdJyMFV3IwOS1B5U"

jwtsecret = "shrinivas"