name = "backend"
compatibility_date = "2024-08-09"

# [vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMDQ2YzQwZTQtYWUzNC00ZWFjLTgwMTktNTgzNmJiMThhZGI3IiwidGVuYW50X2lkIjoiNTA3NWNjY2I0NGM2YmUwNDI0Mjc5NDYwMDg5Y2QxMGJkOWI2YTVmYjFlOWIxMTczZjI0OGJiMGE3ZDM4YjhkNSIsImludGVybmFsX3NlY3JldCI6Ijc5OGI2NjhmLTYxMGUtNGRhZC1iODNjLTdmNjQ2ZDQ3Nzg0NSJ9.RVYJtnP4sBuSHcv5crA-Yc-ZWDrgcpiUq7D7ZjFnFio"